In [2]:
import numpy
import tensorflow as tf
import numpy as np
#print(numpy.__file__)
print((tf.__file__))
a = 'test'
print(a)
a = 'test2'
print(a)
x = tf.constant(1, name="x")
y = tf.constant(2, name="y")
add_op = tf.add(x, y)
with tf.Session() as sess:
    print(sess.run(add_op))
a = [[1, 2], [3, 4]]
print(type(a))
npa = np.array([[1, 2], [3, 4]])
print(type(npa))
npb = np.array([1, 2, 3, 4])
npbb = np.array([1, 2, 3, 4])
print('here')
print(np.dot(npb, npbb))
print(type(npb))
print(npa.T)
print(npa.shape)
print(npa.T.shape)
arr = np.asarray([[1,2,3], [4,5,6]])
print(type(arr))
print(arr.shape)
print(npb.T)
?npb.dot

/Users/i035187/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/tensorflow/__init__.py
test
test2
3
<class 'list'>
<class 'numpy.ndarray'>
here
30
<class 'numpy.ndarray'>
[[1 3]
 [2 4]]
(2, 2)
(2, 2)
<class 'numpy.ndarray'>
(2, 3)
[1 2 3 4]


Docstring:
a.dot(b, out=None)

Dot product of two arrays.

Refer to `numpy.dot` for full documentation.

See Also
--------
numpy.dot : equivalent function

Examples
--------
>>> a = np.eye(2)
>>> b = np.ones((2, 2)) * 2
>>> a.dot(b)
array([[ 2.,  2.],
       [ 2.,  2.]])

This array method can be conveniently chained:

>>> a.dot(b).dot(b)
array([[ 8.,  8.],
       [ 8.,  8.]])
Type:      builtin_function_or_method
